/****************************************************************************
 *
 *   Copyright (C) 2013-2015 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file d:\px4soft\px4\Firmware\msg\actuator_armed.msg */

//用于声纳传感器输出四方测量信息TOP：SonarGroupDistance


#pragma once

#include <stdint.h>
#include <uORB/uORB.h>


#ifndef __cplusplus

#endif

#ifdef __cplusplus
struct __EXPORT SonarGroupDistance_s {
#else
struct SonarGroupDistance_s {
#endif
        uint64_t timestamp;
        int sonar_group_distance[5];    //[height,front,back,left,right]in cm
        bool sonar_group_status[5];      //[height,front,back,left,right]测量状态，1为正常，0为有问题未更新，并保留上一周期测量数据
//        int Height;                 //高度cm
//        int Front;                  //前向cm
//        int Back;                   //后向cm
//        int Left;                   //左侧cm
//        int Right;                  //右侧cm
//        bool Height_Status;         //测量状态，1为正常，0为有问题
//        bool Front_Status;
//        bool Back_Status;
//        bool Left_Status;
//        bool Right_Status;
#ifdef __cplusplus

#endif
};

/* register this as object request broker structure */
ORB_DECLARE(SonarGroupDistance);
